#ifndef H_ERROR
#define H_ERROR

enum Error
{
    INCORRECT_TRANSPORT,
    INCORRECT_DISTANCE,
    INCORRECT_REST_INTERVAL,
    INCORRECT_REST_DURATION,
    INCORRECT_REDUCER,
    INCORRECT_SPEED
};

#endif